package org.apache.ibatis.r2dbc.application.entity.model;

import lombok.*;
import lombok.experimental.Accessors;

import java.time.LocalDateTime;

/**
 * auto generated
 *
 * @author AutoGenerated
 */
@ToString
@Getter
@Setter
@Accessors(chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode
public class Dept {
    /**
     * dept no
     */
    protected Long deptNo;

    /**
     * dept name
     */
    protected String deptName;

    /**
     * location
     */
    protected String location;

    /**
     * create time
     */
    protected LocalDateTime createTime;

}