package org.apache.ibatis.r2dbc.spring.application.entity.model;

import lombok.*;
import lombok.experimental.Accessors;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * auto generated
 *
 * @author AutoGenerated
 */
@ToString
@Getter
@Setter
@Accessors(chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode
public class Emp {
    /**
     * emp no
     */
    protected Long empNo;

    /**
     * emp name
     */
    protected String empName;

    /**
     * job
     */
    protected String job;

    /**
     * manager
     */
    protected String manager;

    /**
     * hire date
     */
    protected LocalDate hireDate;

    /**
     * salary
     */
    protected Integer salary;

    /**
     * kpi
     */
    protected BigDecimal kpi;

    /**
     * dept no
     */
    protected Long deptNo;

    /**
     * create time
     */
    protected LocalDateTime createTime;

}