package org.apache.ibatis.r2dbc.spring.application.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.r2dbc.spring.application.entity.extend.EmpWithDept;
import reactor.core.publisher.Flux;

/**
 * auto generated
 *
 * @author AutoGenerated
 */
@Mapper
public interface EmpMapper {

    Flux<EmpWithDept> selectEmpWithDeptList();
}