package org.apache.ibatis.r2dbc.application.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.r2dbc.application.entity.extend.DeptWithEmp;
import org.apache.ibatis.r2dbc.application.entity.model.Dept;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.time.LocalDateTime;

/**
 * auto generated
 *
 * @author AutoGenerated
 */
@Mapper
public interface DeptMapper {

    Mono<Long> count();

    Flux<Dept> selectAll();

    Mono<Dept> selectOneByDeptNo(Long deptNo);

    Flux<Dept> selectListByTime(LocalDateTime createTime);

    Mono<Integer> insert(Dept dept);

    Mono<Integer> deleteByDeptNo(Long deptNo);

    Mono<Integer> updateByDeptNo(Dept dept);

    Flux<DeptWithEmp> selectDeptWithEmpList();
}