package org.apache.ibatis.r2dbc.application.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.r2dbc.application.entity.extend.EmpWithDept;
import org.apache.ibatis.r2dbc.application.entity.model.Emp;
import reactor.core.publisher.Flux;

/**
 * auto generated
 *
 * @author AutoGenerated
 */
@Mapper
public interface EmpMapper {

    Flux<EmpWithDept> selectEmpWithDeptList();

    Flux<Emp> selectByParameterMap(Emp emp);
}